### PR TITLE
3rd try on de2

### PR DESCRIPTION
**Pull request by PietDelaney**
3rd try on de2

Video still Blank

### CODE REVIEW

**Review by yuri-panchul — CHANGES_REQUESTED** [review]
Pete: you are trying to merge to main branch, but we are doing those changes on new_graphics branch

**Comment by yuri-panchul** [comment]
You need to put 
              w_red         = 10, // 4,
              w_green       = 10, // 4,
              w_blue        = 10, // 4,


Note you have RGB signals each 10-bit wide in *qsf file

**Comment by yuri-panchul** [comment]
Incorporated the changes in a different way. This pull request has to be rebased, otherwise it changes 763 files

**Comment by PietDelaney** [comment]
I modified the your new graphics branch. At least that's what I think. I'll
double check

-piet

**Comment by yuri-panchul** [comment]
> I modified the your new graphics branch. At least that's what I think. I'll double check

No, you were trying to do merge to main without rebase. But it does not matter because I already merged your changes manually, then edited them

**Pull request closed without merging**
